config/routes.rb
TowerDefense::Application.routes.draw do
  root to: 'pages#phaserStars'

  get "login", to: "sessions#login"
  get "logout", to: "sessions#logout"
  post "sessions/login_auth", to: "sessions#login_auth"
  get "scoreboard", to: "pages#scoreboard"
  get "towerDefense", to: "pages#towerDefense"
  get "phaserStars", to: "pages#phaserStars"
  put "update_score", to: "highscores#update"
  put "create_score", to: "highscores#create"

  resources :profiles
  

  

end

app/models/game.rb
class Game < ActiveRecord::Base
  has_many :highscores
end

app/models/highscore.rb
class Highscore < ActiveRecord::Base
  belongs_to :user
  belongs_to :game
end

app/models/user.rb
class User < ActiveRecord::Base
	attr_accessor :password
  before_save :encrypt_password
	after_save :clear_password

  has_many :highscores

	validates :username, :presence => true, :uniqueness => true, :length => { :in => 3..20 }
	validates :password, :confirmation => true
  validates_length_of :password, :in => 6..20, :on => :create

  def self.authenticate(username="", login_password="")
  	user = User.find_by_username(username)
  	if user && user.match_password(login_password)
  		return user
  	else
  		return false
  	end
  end   

  def match_password(login_password="")
  	encrypted_password == BCrypt::Engine.hash_secret(login_password, salt)
  end

  def encrypt_password
  	unless password.blank?
  		self.salt = BCrypt::Engine.generate_salt
  		self.encrypted_password = BCrypt::Engine.hash_secret(password, salt)
  	end
  end

  def clear_password
  	self.password = nil
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_filter :authenticate_user

  protected
  def authenticate_user #Use this on all pages that require a user to be logged in.
    if session[:user_id]
      @current_user = User.find(session[:user_id])
    end
  end

  def is_signed_in?
    return @current_user.present?
  end

  def requires_signed_in
    unless @current_user.present?
      redirect_to login_path
    end
  end
end

app/controllers/highscores_controller.rb
class HighscoresController < ApplicationController
	def create
		@highscore = Highscore.new(highscore_params)
		@highscore.save
		respond_to do |f|
			f.json { render json: @highscore }
		end
	end

	def update
		@highscore = Highscore.find(highscore_params[:id])
		@highscore.update_attributes(highscore_params)
		respond_to do |f|
			f.json { render json: @highscore }
		end
	end

	private
	def highscore_params
		params.require(:highscore).permit(:id, :value, :game_id, :user_id)
	end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

	def scoreboard
		@tdScores = Highscore.joins(:game).where("games.name = ?", "Tower Defense").order("highscores.value DESC")
		@psScores = Highscore.joins(:game).where("games.name = ?", "Phaser Stars").order("highscores.value DESC")
	end

	def towerDefense
		@highscores = Highscore.joins(:game).where("games.name = ?", "Tower Defense").order("highscores.value DESC").first(25)
		if @current_user.present?
			@highscore = Highscore.joins(:game).where("games.name = ? AND user_id = ?", "Tower Defense", @current_user.id).first()
		end
	end

	def phaserStars
		@highscores = Highscore.joins(:game).where("games.name = ?", "Phaser Stars").order("highscores.value DESC").first(25)
		if @current_user.present?
			@highscore = Highscore.joins(:game).where("games.name = ? AND user_id = ?", "Phaser Stars", @current_user.id).first()
		end
	end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
	before_filter :requires_signed_in, :only => [:edit, :update, :show]

	# Signup page
	def new
		if is_signed_in?
			redirect_to root_path
		else
			@user = User.new
		end
	end

	def create
		@user = User.new(user_params)
		if @user.save
			flash[:notice] = "You have successfully registered"
			flash[:color] = "valid"
			session[:user_id] = @user.id
			redirect_to root_path
		else
			flash[:notice] = "Invalid Entry"
			flash[:color] = "invalid"
			render "new"
		end  		
	end

	# edit profile page
	def edit
		@user = User.find(params[:id])
	end

	def update
		@user = User.find(params[:id])
		if @user.update_attributes(params[:user])
			flash[:notice] = "You have successfully updated your profile"
			flash[:color] = "valid"
			redirect_to profil_path
		else
			flash[:notice] = "Invalid Entry"
			flash[:color] = "invalid"
		end  		
		render "edit"
	end

	# profile page
	def show
		@user = User.find(params[:id])
		@tdScore = Highscore.where("user_id = ?", @user.id).joins(:game).where('name = "Tower Defense"')[0]
		@psScore = Highscore.where("user_id = ?", @user.id).joins(:game).where('name = "Phaser Stars"')[0]
	end

	private
	def user_params
		params.require(:user).permit(:username, :password, :password_confirmation)
	end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	before_filter :authenticate_user, :only => [:logout]

	def login
		if is_signed_in?	
			redirect_to root_path
		end
	end

	def login_auth
		authorized_user = User.authenticate(params[:username], params[:password])
		if authorized_user
			session[:user_id] = authorized_user.id
			flash[:notice] = "Welcome back #{authorized_user.username}"
			flash[:color] = "valid"
			redirect_to request.env['HTTP.REFERER'] || root_path
		else
			flash[:notice] = "Invalid Username or Password"
			flash[:color] = "invalid"
			render "login"
		end  		
	end

	def logout
		requires_signed_in
		session[:user_id] = nil
		redirect_to root_path
	end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def is_signed_in?
    return @current_user.present?
  end

end

app/views/layouts/_footer.erb
<!-- Footer -->
  <footer class="row">
    <div class="large-12 columns">
      <hr />
      <div class="row">
        <div class="large-6 columns">
          <p style="font-size:12px;">Created by <a href="http://www.about.me/JonKoehmstedt">Jon Koehmstedt</a> &copy; 2014</p>
        </div>
      </div>
    </div>
  </footer>    

app/views/layouts/_nav_right.html.erb
<% if is_signed_in? %>
	<li style="width:115px"><%= link_to :Profile, profile_path(@current_user), class: "button" %></li>
	<li style="width:115px"><%= link_to :Logout , :logout, class: "button" %></li> 
<%else%>
	<li style="width:115px"><%= link_to :Signup , new_profile_path, class: "button"%></li>
	<li style="width:115px"><%= link_to :Login , :login, class: "button"%></li>  
<% end %>

app/views/layouts/_notice.html.erb
<% if flash[:color] == "valid" %>
  <div class="valid_notice">
    <p><%= flash[:notice]%></p>
  </div>
<% elsif flash[:color] == "invalid"%>
  <div class="invalid_notice">
    <p><%=flash[:notice]%></p>
  </div>
<% else %>
  <div class="notice">
    <p><%=flash[:notice]%></p>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title><%= yield(:title) %></title>
    <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= csrf_meta_tags %>
  </head>
    <%= yield %>
    <%= render 'layouts/footer' %>

    <%= javascript_include_tag "application", "data-turbolinks-track" => true  %>
  </body>
</html>

app/views/pages/scoreboard.html.erb
<body id="towerBackground">
<!-- NAVIGATION BAR -->
  <div class="fixed" style="margin-bottom:50px">
    <nav>
      <div class="Main_Header">
        <%= link_to "", towerDefense_path, class: "headerLink" %>
        <ul class="button-group radius" style="float:right; padding:13px 13px 0 13px;">
          <li style="width:150px, height:50px">
            <%= link_to "Phaser Stars", phaserStars_path, class: "button" %>
          </li>
          <li style="width:150px, height:50px">
            <%= link_to "Tower Defense", towerDefense_path, class: "button" %>
          </li>
            <%= render 'layouts/nav_right' %> 
        </ul>
      </div>
      <% if flash[:color]== "valid" %>
        <div class="valid_notice">
      <% elsif flash[:color]== "invalid"%>
        <div class="invalid_notice">
      <% else %>
        <div class="notice">
      <% end %>
          <p><%= flash[:notice]%></p>
        </div>
    </nav>
  </div>
  <div class="row" style="margin-bottom: 130px"></div>
  <!-- END NAVIGATION BAR -->


  <% content_for :title, "Tower Defense | Scoreboard" %>
<div class="row">
	<div class="small-6 columns">
		<h2 style="text-align: right; padding: 0 15px">Tower Defense High Scores</h2>
		<div class="large-10 large-offset-2 columns">
			<table class="longScoreboard">
				<tr>
					<thead>
						<th style="width:10%">Rank</th>
						<th style="width:55%">Username</th>
						<th style="width:45%">High Score</th>
					<thead>
				</tr>
		        <tbody>
					<%	@tdScores.each_with_index do |score, index| %>
					<tr>
						<td style="text-align:center"><%= index + 1 %></td>
						<td><%= score.user.username %></td>
						<td><%= score.value %></td>
					</tr>
					<% end %>
				</tbody>
			</table>
		</div>
	</div>
	<div class="small-6 columns">	
		<h2 style="padding: 0 15px">Phaser Stars High Scores</h2>
		<div class="large-10 columns end">
			<table class="longScoreboard">
				<thead>
					<tr>
						<th style="width:10%">Rank</th>
						<th style="width:55%">Username</th>
						<th style="width:45%">High Score</th>
					</tr>
		        </thead>
		        <tbody>
					<%	@psScores.each_with_index do |score, index| %>
					<tr>
						<td style="text-align:center"><%= index + 1 %></td>
						<td><%= score.user.username %></td>
						<td><%= score.value %></td>
						</tr>
					<% end %>
				</tbody>
			</table>
		</div>
	</div>
</div>

app/views/pages/template.html.erb
<div class="row">
    <div class="large-12 columns">
      <div class="nav-bar right">
       <ul class="button-group">
         <li><a href="#" class="button">Link 1</a></li>
         <li><a href="#" class="button">Link 2</a></li>
         <li><a href="#" class="button">Link 3</a></li>
         <li><a href="#" class="button">Link 4</a></li>
        </ul>
      </div>
      <h1>Blog <small>This is my blog. It's awesome.</small></h1>
      <hr />
    </div>
  </div>
  <!-- End Nav -->
 
 
  <!-- Main Page Content and Sidebar -->
  <div class="row">
    <!-- Main Blog Content -->
    <div class="large-9 columns" role="content">
 
      <article>
 
        <h3><a href="#">Blog Post Title</a></h3>
        <h6>Written by <a href="#">John Smith</a> on August 12, 2012.</h6>
 
        <div class="row">
          <div class="large-6 columns">
            <p>Bacon ipsum dolor sit amet nulla ham qui sint exercitation eiusmod commodo, chuck duis velit. Aute in reprehenderit, dolore aliqua non est magna in labore pig pork biltong. Eiusmod swine spare ribs reprehenderit culpa.</p>
            <p>Boudin aliqua adipisicing rump corned beef. Nulla corned beef sunt ball tip, qui bresaola enim jowl. Capicola short ribs minim salami nulla nostrud pastrami.</p>
          </div>
          <div class="large-6 columns">
            <img src="http://placehold.it/400x240&text=[img]" />
          </div>
        </div>
        <p>Pork drumstick turkey fugiat. Tri-tip elit turducken pork chop in. Swine short ribs meatball irure bacon nulla pork belly cupidatat meatloaf cow. Nulla corned beef sunt ball tip, qui bresaola enim jowl. Capicola short ribs minim salami nulla nostrud pastrami. Nulla corned beef sunt ball tip, qui bresaola enim jowl. Capicola short ribs minim salami nulla nostrud pastrami.</p>
        <p>Pork drumstick turkey fugiat. Tri-tip elit turducken pork chop in. Swine short ribs meatball irure bacon nulla pork belly cupidatat meatloaf cow. Nulla corned beef sunt ball tip, qui bresaola enim jowl. Capicola short ribs minim salami nulla nostrud pastrami.</p>
      </article>
 
      <hr />
 
      <article>
        <h3><a href="#">Blog Post Title</a></h3>
        <h6>Written by <a href="#">John Smith</a> on August 12, 2012.</h6>
        <div class="row">
          <div class="large-6 columns">
            <p>Bacon ipsum dolor sit amet nulla ham qui sint exercitation eiusmod commodo, chuck duis velit. Aute in reprehenderit, dolore aliqua non est magna in labore pig pork biltong. Eiusmod swine spare ribs reprehenderit culpa.</p>
            <p>Boudin aliqua adipisicing rump corned beef. Nulla corned beef sunt ball tip, qui bresaola enim jowl. Capicola short ribs minim salami nulla nostrud pastrami.</p>
          </div>
          <div class="large-6 columns">
            <img src="http://placehold.it/400x240&text=[img]" />
          </div>
        </div>
        <p>Pork drumstick turkey fugiat. Tri-tip elit turducken pork chop in. Swine short ribs meatball irure bacon nulla pork belly cupidatat meatloaf cow. Nulla corned beef sunt ball tip, qui bresaola enim jowl. Capicola short ribs minim salami nulla nostrud pastrami. Nulla corned beef sunt ball tip, qui bresaola enim jowl. Capicola short ribs minim salami nulla nostrud pastrami.</p>
        <p>Pork drumstick turkey fugiat. Tri-tip elit turducken pork chop in. Swine short ribs meatball irure bacon nulla pork belly cupidatat meatloaf cow. Nulla corned beef sunt ball tip, qui bresaola enim jowl. Capicola short ribs minim salami nulla nostrud pastrami.</p>
      </article>
    </div>
    <!-- End Main Content -->
 
    <!-- Sidebar -->
    <aside class="large-3 columns">
      <h5>Categories</h5>
      <ul class="side-nav">
        <li><a href="#">News</a></li>
        <li><a href="#">Code</a></li>
        <li><a href="#">Design</a></li>
        <li><a href="#">Fun</a></li>
        <li><a href="#">Weasels</a></li>
      </ul>
 
      <div class="panel">
        <h5>Featured</h5>
        <p>Pork drumstick turkey fugiat. Tri-tip elit turducken pork chop in. Swine short ribs meatball irure bacon nulla pork belly cupidatat meatloaf cow.</p>
        <a href="#">Read More &rarr;</a>
      </div>
    </aside>
    <!-- End Sidebar -->
  </div>
  <!-- End Main Content and Sidebar -->
 
 
  <!-- Footer -->
  <footer class="row">
    <div class="large-12 columns">
      <hr />
      <div class="row">
        <div class="large-6 columns">
          <p>&copy; Copyright no one at all. Go to town.</p>
        </div>
        <div class="large-6 columns">
          <ul class="inline-list right">
            <li><a href="#">Link 1</a></li>
            <li><a href="#">Link 2</a></li>
            <li><a href="#">Link 3</a></li>
            <li><a href="#">Link 4</a></li>
          </ul>
        </div>
      </div>
    </div>
  </footer>

app/views/pages/towerDefense.html.erb
<body id="towerBackground">
  <!-- NAVIGATION BAR -->
  <div class="fixed" style="margin-bottom:50px">
    <nav>
      <div class="Main_Header">
        <%= link_to "", towerDefense_path, class: "headerLink" %>
        <ul class="button-group radius" style="float:right; padding:13px 13px 0 13px;">
          <li style="width:150px, height:50px">
            <%= link_to "Phaser Stars", phaserStars_path, class: "button" %>
          </li>
          <li style="width:170px"><%= link_to :ScoreBoard, scoreboard_path, class: "button" %></li>
            <%= render 'layouts/nav_right' %> 
        </ul>
      </div>
        <%= render 'layouts/notice' %>
    </nav>
  </div>
  <div class="row" style="margin-bottom: 130px"></div>
  <!-- END NAVIGATION BAR -->
  <% content_for :title, "Tower Defense" %>
  <%= javascript_include_tag "phaser.min" %>
  <!-- Main Page Content and Sidebar -->
  <div class="row">
    <!-- Main Blog Content -->
    <div class="large-9 columns" role="content">
      <div id="gameWindow"></div>
    </div>
    <!-- End Main Content -->

    <!-- Sidebar -->
    <aside class="large-3 columns" style="padding: 0px">
      <div class="highscore10 scoreboard">
        <h4 style="text-align:center">Top 10 High Scores</h4>
        <ul class="side-nav">
         <li style="width: 80px;float:right"><strong>High Score</strong></li>
         <li style="width: 165px;text-align:left"><strong>Username</strong></li>
         <%	@highscores.each_with_index do |score, i| %>
         <li style="width: 65px;float:right"><%= score.value %></li>
         <li style="width: 175px;text-align:left"><%= (i+1).to_s + ".) " + score.user.username %></li>
         <% end %>
       </ul>
     </div>

     <div class="panel">
      <h5>Place Ad Here</h5>
      <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris</p>
      <a href="#">CLICK HERE!!! &rarr;</a>
    </div>
  </aside>
  <!-- End Sidebar -->
  </div>
  <!-- End Main Content and Sidebar -->

app/views/profiles/new.html.erb
<body>
  <!-- NAVIGATION BAR -->
  <div class="fixed" style="margin-bottom:50px">
    <nav>
      <div class="Main_Header">
        <%= link_to "", towerDefense_path, class: "headerLink" %>
        <ul class="button-group radius" style="float:right; padding:13px 13px 0 13px;">
          <li style="width:150px, height:50px">
            <%= link_to "Tower Defense", towerDefense_path, class: "button" %>
          </li>
          <li style="width:150px, height:50px">
            <%= link_to "Phaser Stars", phaserStars_path, class: "button" %>
          </li>
          <li style="width:170px"><%= link_to :ScoreBoard, scoreboard_path, class: "button" %></li>
            <%= render 'layouts/nav_right' %> 
        </ul>
      </div>
        <%= render 'layouts/notice' %>
    </nav>
  </div>
  <div class="row" style="margin-bottom: 130px"></div>
  <!-- END NAVIGATION BAR -->




<% content_for :title, "Tower Defense | Signup" %>
<div class= "Sign_Form">
  <h1>Sign Up</h1>
  <%= form_for(:user, :url => {:controller => 'profiles', :action => 'create'}) do |f| %>

    <p>Username:</br> <%= f.text_field :username, class: "Sign_Form_Field" %></p>
    <p>Password:</br> <%= f.password_field :password, class: "Sign_Form_Field" %></p>
    <p>Password Confirmation:</br> <%= f.password_field :password_confirmation, class: "Sign_Form_Field" %></p>
    <%= f.submit :Signup %>
  <% end %>
  <% if @user.errors.any? %>
	<ul class="Signup_Errors">
		<% for message_error in @user.errors.full_messages %>
			<li>* <%= message_error %></li>
	  	<% end %>
	</ul>
  <% end %>
</div>

app/views/profiles/show.html.erb
<body id="towerBackground">
  <!-- NAVIGATION BAR -->
  <div class="fixed" style="margin-bottom:50px">
    <nav>
      <div class="Main_Header">
        <%= link_to "", towerDefense_path, class: "headerLink" %>
        <ul class="button-group radius" style="float:right; padding:13px 13px 0 13px;">
          <li style="width:150px, height:50px">
            <%= link_to "Tower Defense", towerDefense_path, class: "button" %>
          </li>
          <li style="width:150px, height:50px">
            <%= link_to "Phaser Stars", phaserStars_path, class: "button" %>
          </li>
          <li style="width:170px"><%= link_to :ScoreBoard, scoreboard_path, class: "button" %></li>
            <%= render 'layouts/nav_right' %> 
        </ul>
      </div>
        <%= render 'layouts/notice' %>
    </nav>
  </div>
  <div class="row" style="margin-bottom: 130px"></div>
  <!-- END NAVIGATION BAR -->




<% content_for :title, "Profile Page | "+@user.username %>
<div class="row">
	<h1><%= "Profile Page: " + @user.username%></h1>
	<br/>
	<p>Username: <%= @user.username %></p>
  <% if @tdScore.present? %>
  	<p>Tower Defense High Score: <%= @tdScore.value %> </p>
  <% end %>
  <% if @psScore.present? %>
    <p>Phaser Stars High Score: <%= @psScore.value %> </p>
  <% end %>
</div>